security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        users_in_memory: { memory: null }
    password_hasher:
            class: App\Entity\User
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { host: admin.%app.host%, roles: ROLE_ADMIN }
         - { host: moderator.%app.host%, roles: ROLE_MODERATOR }
        # - { path: ^/profile, roles: ROLE_USER }
    role_hierarchy:
      ROLE_ADMIN: [ROLE_MODERATOR, ROLE_USER]
